name: NSE Auto Download
on:
  schedule:
    - cron: "10 6 * * *"   # 11:40 AM IST
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install --upgrade pip
      - run: pip install pandas requests openpyxl xlrd
      - run: python download_nse.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fiidata/*
          git commit -m "Auto-update NSE data" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


